# == Synopsis
#   This file contains the Kwalify YAML schema for the resat config file
#
#   The resat config file is used to specify the API URI components as
#   well as any required auxiliary information (such as username/password)
#
#   The params and headers collections define request parameters and headers
#   that will be sent with every API calls.
#

# Schema for resat configuration
type:  map
class: Resat::Config
mapping:
    "host":     { type: str, required: yes } # Default host
    "port":     { type: int }                # Default port (optional)
    "base_url": { type: str }                # Default base URL (optional)
    "use_ssl":  { type: bool, default: no }  # http or https? (http by default)
    "username": { type: str }                # Basic auth username (optional)
    "password": { type: str }                # Basic auth password (optional)
    "params":                                # Parameters used for all requests
        &name_value_pairs
        type: seq
        sequence:
            - type: map
              mapping: 
                  "name":  { type: str, required: yes, unique: yes }
                  "value": { type: str, required: yes }
    "headers":   *name_value_pairs           # Headers used for all requests
    "variables": *name_value_pairs           # Global variables 

